---
version: "3"
services:
  haproxy:
    container_name: haproxy-container
    image: haproxy:alpine
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 80:80
    networks:
      - app_network
    depends_on:
      - nginx
      - php
  nginx:
    container_name: nginx-container
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    networks:
      - app_network
    depends_on:
      - php
  php:
    container_name: php-container
    image: php:8.2-fpm-alpine
    volumes:
      - ./php:/var/www/html
    ports:
      - 9000:9000
    networks:
      - app_network
networks:
  app_network:
